chore(Node): add umi.js into Node
github/gitignore pull request #3657
Opened 2021-02-17 12:08 UTC by ycjcl868

**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:**

_TODO_

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

2021-02-27 15:58 UTC, bl-ue requested changes
Please remove `.DS_Store`.  This is provided by `macOS.gitignore`.

2021-03-02 07:45 UTC, ycjcl868 commented
> Please remove `.DS_Store`. This is provided by `macOS.gitignore`.

done

2021-03-02 12:22 UTC, bl-ue approved these changes

2021-03-19 06:32 UTC, ycjcl868 commented
ping

2021-06-10 04:00 UTC, closed without merging