Updated for v9
github/gitignore pull request #3735
Opened 2021-05-13 16:23 UTC by richarth

Umbraco 9 now stores its various auto generated files within the umbraco directory whereas older versions of Umbraco stored them in App_Data.  I've therefore added the Umbraco 9 paths.

2021-05-13 16:27 UTC, bl-ue approved these changes

2021-05-14 12:00 UTC, soreng commented
I would suggest creating a new version for v9, since there are a lot of changes that can be very hard to cover with a single version.

2021-05-25 10:39 UTC, martinwoodward requested changes
Can we provide more links to the documentations / discussions around this one.  See also #3739 which was suggesting a broader exclusion of `ood.flag` due to configurability settings.

2021-05-27 23:24 UTC, CertifiedRice approved these changes

2021-07-30 12:21 UTC, soreng commented
> Can we provide more links to the documentations / discussions around this one. See also #3739 which was suggesting a broader exclusion of `ood.flag` due to configurability settings.

Hi,

It's getting closer to a release of Umbraco v9, so we not have a better understanding of what to include / exclude. A lot of folder have been removed since the move from .Net Framework to .Net 5, thus removing the App_Data completely.

I will make a PR with a new, and very limited, file, that we can build upon. Umbraco v8 will still be used for some time, so is there a way to (maybe with a tag) to make a version of the file, or should the file be just for the current version (v8 today, v9 later)?

2025-12-01 16:31 UTC, closed without merging