Add .gitignore for Microsoft Business Central
github/gitignore pull request #3871
Opened 2021-11-02 09:57 UTC by GuillemPM

**Reasons for making this change:**

Dynamics 365 Business Central is a Microsoft solution used by thousands of companies.
We as developers have to use external services in order to get a .gitignore template which is outdated or quite simple.

**Links to documentation supporting these rule changes:**

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-reference-overview
https://gitignore.io/api/AL

If this is a new template:

 - **Link to application or project’s homepage**: 
https://dynamics.microsoft.com/en-us/business-central/overview/
https://github.com/microsoft/AL

2021-12-04 22:44 UTC, bdougie commented
Thanks for the contribution, however per the contribution guidelines this file should be placed in the community folder. Please edit the location of the file. 

https://github.com/github/gitignore#specialized-templates

2021-12-04 22:50 UTC, bdougie requested changes
please move to the community folder

2021-12-05 07:27 UTC, JeremyVyska commented
For what it's worth, this version is much better than #2743 for general use.

@bdougie - question for you, if you'd be so kind:  The reason folks are trying to support AL language gitignore files is because that will add them to the "Add a .gitignore file" dropdown.  I notice that the community folder ones are not in that list.   Is there a smart way that one could create new AL repos using the gitignore from the community folder?

2021-12-05 14:00 UTC, GuillemPM commented
I agree with @JeremyVyska as AL is a language that repositories are totally based on. If it's possible we would like to have direct access to the template in Add .gitignore at repository creation time

2021-12-05 14:00 UTC, GuillemPM commented
> For what it's worth, this version is much better than #2743 for general use.
> 
> 
> 
> @bdougie - question for you, if you'd be so kind:  The reason folks are trying to support AL language gitignore files is because that will add them to the "Add a .gitignore file" dropdown.  I notice that the community folder ones are not in that list.   Is there a smart way that one could create new AL repos using the gitignore from the community folder? 

I agree with @JeremyVyska as AL is a language that repositories are totally based on. If it's possible we would like to have direct access to the template in Add .gitignore at repository creation time

2021-12-07 06:46 UTC, bdougie commented
@JeremyVyska thanks for the input and the context @GuillemPM. I will go ahead and merge as-is.

2021-12-07 06:46 UTC, bdougie approved these changes

2021-12-07 06:46 UTC, merged