Create TypeScript.gitignore
github/gitignore pull request #3933
Opened 2021-12-22 13:23 UTC by Tyler887

**Reasons for making this change:**

Just because I need TS Gitignore!

**Links to documentation supporting these rule changes:**

https://www.typescriptlang.org/docs/

If this is a new template:

 - **Link to application or project’s homepage**: https://typescriptlang.org

2021-12-27 05:20 UTC, SuperZooper3 commented
There seems to be a more comprehensive gitinore here: https://github.com/microsoft/TypeScript-Node-Starter/blob/master/.gitignore . I sugest we use this one instead?

2021-12-27 08:13 UTC, Polda18 commented
Are you sure you understand what `.gitignore` means? Do you understand how it works? I think that you may want Typescript files to remain instead of being ignored, right? Typescript is the source code you want to be included in the project, you don't want the resulting Javascript files to be included in the project. Unfortunately, that's something that isn't quite easy to be set up via a single universal `.gitignore` file, it needs to be set up individually for each specific project and kept up to date.

2021-12-27 08:50 UTC, Tyler887 commented
> Are you sure you understand what `.gitignore` means? Do you understand how it works? I think that you may want Typescript files to remain instead of being ignored, right? Typescript is the source code you want to be included in the project, you don't want the resulting Javascript files to be included in the project. Unfortunately, that's something that isn't quite easy to be set up via a single universal `.gitignore` file, it needs to be set up individually for each specific project and kept up to date.

Changed everything up to match the other repo.

2021-12-27 08:55 UTC, Tyler887 commented
> There seems to be a more comprehensive gitinore here: https://github.com/microsoft/TypeScript-Node-Starter/blob/master/.gitignore . I sugest we use this one instead?

We can make it easier to find it after the most recent [commit](https://github.com/github/gitignore/pull/3933/commits) to the `TypeScript.gitignore` file.

2021-12-29 19:47 UTC, SuperZooper3 commented
Should also add the source of the gitignore to the top. It's under MIT as well so that should be added.

2021-12-29 20:26 UTC, Tyler887 commented
> Should also add the source of the gitignore to the top. It's under MIT as well so that should be added.

Thanks! Addressed and noted source. ;)

2025-01-17 21:07 UTC, dooleydevin requested changes
Apologies for the late feedback! Everything here looks good other than the lines I called out. We don't want to have overlap within the templates, and ignoring the entirety of directories like `.idea` can have unintended consequences 🙂

2025-01-17 21:07 UTC, dooleydevin commented on TypeScript.gitignore
> +Thumbs.db
Per our contribution guidelines, we don't include OS or editor specific files in our gitignore templates.

Do you mind removing these lines?

2025-04-11 19:50 UTC, wirecat commented
@Tyler887 Closing for now since we haven't heard anything after @dooleydevin's review. Please feel free to re-open once you're ready to engage with us on the change.

2025-04-11 19:50 UTC, closed without merging