Update Python.gitignore
github/gitignore pull request #4156
Opened 2022-09-18 10:09 UTC by MaxBui95

**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:**

_TODO_

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

2022-09-20 16:16 UTC, prashantk01 approved these changes

2022-09-21 11:31 UTC, mvolfik requested changes

2022-09-21 11:31 UTC, mvolfik commented on Python.gitignore
> + Byte-compiled / optimized / DLL files
```suggestion
# Byte-compiled / optimized / DLL files
```

This is a comment, so keep the `#` at the beginning

2022-09-21 11:31 UTC, mvolfik commented on Python.gitignore
> + .idea/
This isn't from Python, but from Jetbrains editors/IntelliJ

2022-09-21 11:31 UTC, mvolfik commented on Python.gitignore
> + env/
Is this created by default or has some special meaning for Python? If it's just a convention or your preference to create this folder, it shouldn't be included here

2022-09-26 02:38 UTC, Gatito1010 commented
Gracias error mio noe avía dado cuenta lo arreglo gracias

2025-12-05 16:32 UTC, closed without merging