Node.gitignore include support for SvelteKit, Vite, Firebase, and .env.example
github/gitignore pull request #4298
Opened 2023-05-23 04:26 UTC by taronaeo

**Reasons for making this change:**

1. SvelteKit - Upon running `npm run build` / `yarn build`, Vite generates a .svelte-kit folder that should not be part of the Git repository.
2. .env.example - Examples of environment files should be part of the Git repository for setup and reference.
3. Vite - Vite may generate temporary log files in the project that may be accidentally committed.
4. Firebase - `firebase-tools` generates cache directory `.firebase` to speed up build processes. Not strictly needed in the Git repository.

**Links to documentation supporting these rule changes:**

1. Firebase - https://stackoverflow.com/a/52131191

2023-12-13 11:24 UTC, spirit-x64 commented
Second case (`.env.example`) should be fixed by #4234

2025-06-24 00:01 UTC, dooleydevin requested changes
@taronaeo it looks like there are merge conflicts here based on upstream changes to the `.env` patterns and yarn v3 patterns. Once those are resolved, this looks good to merge to me 😄 

Also left a couple small suggestions, though I don't consider them blocking for this PR to be merged.

2025-06-24 00:01 UTC, dooleydevin commented on Node.gitignore
> +.svelte-kit
A small nitpick: adding a trailing slash here will make sure this only matches directories with this name.

```suggestion
.svelte-kit/
```

2025-06-24 00:01 UTC, dooleydevin commented on Node.gitignore
> +.firebase
Similar request to the one above:


```suggestion
.firebase/
```

2025-06-26 13:06 UTC, taronaeo commented
@dooleydevin I've resolved all conflicts and merged your suggested changes, PTAL again :)

2025-06-26 16:45 UTC, dooleydevin requested changes
@taronaeo sorry for the back-and-forth here. One more request regarding the dotenv file matching before this is ready to merge 👍

2025-06-26 16:45 UTC, dooleydevin commented on Node.gitignore
> +.env.local
Do you mind reverting this so that we take the upstream change here?

I've seen patterns like `.env.development` and `.env.production` (without the `.local` suffix). Looking around online that seems pretty common. I'd prefer we exclude all `.env.*` patterns except for `.env.example` for that reason 👍

2025-06-26 16:55 UTC, taronaeo commented on Node.gitignore
> +.env.local
Reverted! Feel free to review again! :)

2025-06-26 17:02 UTC, dooleydevin approved these changes
Thanks for the contribution and for addressing feedback quickly! And apologies for the delay on initial review, us new maintainers are still trying to get on top of the backlog.

2025-06-26 17:02 UTC, merged

2026-03-14 08:29 UTC, Sum1cares approved these changes