Update Java.gitignore
github/gitignore pull request #4452
Opened 2024-05-30 12:14 UTC by ayush8914

specified few files and directory name

2024-05-30 17:15 UTC, wirecat requested changes
Thank you for contributing! There's a few points I'd like to discuss further.

Also, can you please provide more details about your changes? Please see our [contribution guidelines](https://github.com/github/gitignore/blob/main/README.md#contributing-guidelines) for more details.

2024-05-30 17:15 UTC, wirecat commented on Java.gitignore
> +.classpath
We have an [eclipse specific](https://github.com/github/gitignore/blob/main/Global/Eclipse.gitignore) template and would prefer to not include IDE specific config in language templates.

2024-05-30 17:15 UTC, wirecat commented on Java.gitignore
> +build/
See the comment about the eclipse specific template. I would prefer we create a new Global entry for Gradle.

In addition, we could also consider adding a descriptive comment and leaving these entries, but having them commented out by default.
[Example of this in the Python template.](https://github.com/github/gitignore/blob/main/Python.gitignore#L157-L162)

2024-05-31 14:15 UTC, ayush8914 commented
yaa, that's right.

2024-05-31 14:15 UTC, closed without merging