Update Terraform.gitignore
github/gitignore pull request #4455
Opened 2024-06-02 16:51 UTC by RScrafted

Added line to ignore graph file('s).

**Reasons for making this change:**

In my personal project, I have included generating terraform graph saving with a .dot extension which is standard with terraform. I noticed the default template was missing to ignore graph files which are mostly optional in most cases. As a result, I have added the same.

**Links to documentation supporting these rule changes:**

https://developer.hashicorp.com/terraform/cli/commands/graph

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

2024-06-05 23:13 UTC, RScrafted reviewed
Added other formats to be ignored

2025-07-17 19:26 UTC, thorrsson commented
Personally I've committed the graph files to code bases before, @RScrafted would you be on board with commenting out the line but leaving it in the .gitignore file as optional with some commentary?

2025-07-17 19:36 UTC, thorrsson requested changes
Some feedback on this PR, I think there are a number of items we need to remove from this PR before it could be merged and consumed by the community

2025-07-17 19:36 UTC, thorrsson commented on Terraform.gitignore
> +.DS_Store
```suggestion
```

Could you please remove this OS specific line? We encourage people to instead use global gitignore configs and have a collection of them that can be used. Please see our [Global/README](https://github.com/github/gitignore/blob/main/Global/README.md) for more information and [Global/macOS.gitignore](https://github.com/github/gitignore/blob/main/Global/macOS.gitignore) for an example.

2025-07-17 19:36 UTC, thorrsson commented on Terraform.gitignore
> +.terraform.lock.hcl
https://developer.hashicorp.com/terraform/language/files/dependency-lock#lock-file-location, specifically this section is contrary to your proposed change:

You should include this file in your version control repository so that you can discuss potential changes to your external dependencies via code review, just as you would discuss potential changes to your configuration itself.

```suggestion
```

2025-07-17 19:36 UTC, thorrsson commented on Terraform.gitignore
> +*.terraform.*
This is a bit dangerous
if for some reason I name a module `thorrsson.terraform.tf` I won't be able to commit it.

```suggestion
```

2025-07-17 19:36 UTC, thorrsson commented on Terraform.gitignore
> +# Ignore plan files (optional) as some might save plan before destroy the terraform configuration
If this is optional (per the comment) let's just comment out the line and let folks uncomment if they need to

2025-07-17 19:36 UTC, thorrsson commented on Terraform.gitignore
> +.vscode
We get this quite a bit, but this change is not something that we can accept. The .vscode folder is the workspace folder and is intended to house workspace configuration/settings. We don't want to globally ignore this folder for that reason.
Please read more about the workspace folder here: [Workspace settings documentation](https://code.visualstudio.com/docs/configure/settings#_workspace-settings)

```suggestion
```

2025-07-17 19:36 UTC, thorrsson commented on Terraform.gitignore
> +*.out
Given the naming of the plan files is entirely user-driven I don't think we can assume that every user of terraform will name their plan outputs $something.out

2025-07-18 10:14 UTC, RScrafted commented on Terraform.gitignore
> +.terraform.lock.hcl
Thanks @thorrsson! You're right — I've removed .terraform.lock.hcl from the ignore list since it's recommended to include it in version control.

2025-07-18 10:20 UTC, RScrafted commented on Terraform.gitignore
> +*.terraform.*
Thanks for the note! Since `.terraform/` is already ignored in the terraform.gitignore, I’ve removed the overly broad *.terraform.* pattern to avoid accidentally ignoring valid files.

2025-07-18 10:26 UTC, RScrafted commented on Terraform.gitignore
> +.DS_Store
Thank you so much for the helpful feedback! I really appreciate the guidance on best practices. I’ve removed `.DS_Store` from the `.gitignore` since I understand it’s better handled via global gitignore configs. Looking forward to learning more from the team!

2025-07-18 10:35 UTC, RScrafted commented on Terraform.gitignore
> +# Ignore plan files (optional) as some might save plan before destroy the terraform configuration
Thank you for the helpful suggestion! I’ve updated the `.gitignore` to comment out the `planout` line with an explanation so users can enable it if they wish. I appreciate your guidance!

2025-07-18 10:38 UTC, RScrafted commented on Terraform.gitignore
> +*.out
Thank you — that makes sense. I’ve removed the `*.out` pattern since plan file naming is user-defined and this could unintentionally ignore unrelated files. Appreciate the thoughtful feedback!

2025-07-18 10:40 UTC, RScrafted commented on Terraform.gitignore
> +.vscode
Thank you @thorrsson for being kind and explaining — I understand now why `.vscode/` shouldn't be globally ignored. I've removed that line from the PR. I appreciate the opportunity to learn from your feedback!

2025-07-18 10:54 UTC, RScrafted commented
> Personally I've committed the graph files to code bases before, @RScrafted would you be on board with commenting out the line but leaving it in the .gitignore file as optional with some commentary?

Thanks so much for your input! I’ve commented out the `*.dot` line and added a note so users can choose whether to ignore it based on their workflow. Really appreciate your insight!

2025-07-18 11:26 UTC, RScrafted commented
Hi @thorrsson! Just wanted to check in — I believe I’ve addressed all requested changes, including:

* Commenting out the `*.dot` line as optional, per the earliest feedback
* Commenting out `planout` with a note so users can enable it if needed
* Removing `.terraform.lock.hcl` from ignores based on Terraform’s recommendation
* Removing the `*.terraform.*` pattern due to potential false positives
* Removing `.DS_Store` to respect global gitignore best practices
* Removing the overly broad `*.out` pattern to avoid unintended ignores
* Removing `.vscode` folder ignore to keep workspace settings shareable

Please let me know if anything else needs attention. Thanks again for the review and support!

2025-07-21 18:41 UTC, thorrsson approved these changes

2025-07-21 18:41 UTC, merged

2025-07-21 18:41 UTC, thorrsson commented
Thanks @RScrafted

2025-07-25 18:43 UTC, yehtikezc4732-rgb commented
https://github.com/github/gitignore.git