Update Linux.gitignore
github/gitignore pull request #4489
Opened 2024-07-31 12:54 UTC by mattalxndr

**Reasons for making this change:**

I was comparing my global gitignore with the offerings here and I noticed some holes that could be filled.

**Links to documentation supporting these rule changes:**

- [`man nohup`](https://man7.org/linux/man-pages/man1/nohup.1.html)

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

2024-08-30 20:43 UTC, dooleydevin requested changes
Thanks for this contribution! Just one small request to remove the duplicate `.directory` path 😄

2024-08-30 20:43 UTC, dooleydevin commented on Global/Linux.gitignore
> +.directory
This is actually already included on [lines 6-7 above](https://github.com/github/gitignore/pull/4489/files#diff-8704ae78f5e916819383a0c34fab3c7d7acdc2b6fc15dd189184780821f734edR6-R7)!

2025-01-22 22:31 UTC, asummerford approved these changes

2025-03-07 19:58 UTC, wirecat commented on Global/Linux.gitignore
> +.directory
@mattalxndr Are you available and willing to make that change?

2025-04-07 16:40 UTC, merged